In [11]:
import seaborn as sns

iris = sns.load_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
type(iris)

pandas.core.frame.DataFrame

In [13]:
bit_sequence_1 = iris["sepal_width"] == 3.8

In [14]:
type(bit_sequence_1)

pandas.core.series.Series

In [15]:
bit_sequence_1

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: sepal_width, Length: 150, dtype: bool

In [16]:
bit_sequence_2 = iris["petal_length"] == 1.9

In [17]:
iris[bit_sequence_1]

     sepal_length  sepal_width  petal_length  petal_width    species
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
44            5.1          3.8           1.9          0.4     setosa
46            5.1          3.8           1.6          0.2     setosa
117           7.7          3.8           6.7          2.2  virginica
131           7.9          3.8           6.4          2.0  virginica

In [18]:
iris[bit_sequence_2]

    sepal_length  sepal_width  petal_length  petal_width species
24           4.8          3.4           1.9          0.2  setosa
44           5.1          3.8           1.9          0.4  setosa

In [19]:
iris[bit_sequence_1 & bit_sequence_2]

    sepal_length  sepal_width  petal_length  petal_width species
44           5.1          3.8           1.9          0.4  setosa